# context
server.servlet.context-path=/crczp-guacamole/api/v1
server.port=8087
## microservice name which is used in user management service for identification of this service, e.g. training
microservice.name=guacamole-service
# calling user-and-group service
user-and-group-server.uri=https://172.19.0.22/user-and-group/api/v1
# calling sandbox service
sandbox-service.uri=http://localhost:8080/crczp-openstack/api/v1
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url=jdbc:h2:mem:guacamole-service
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
## overwrite default logback configuration file, e.g., /etc/crczp/logback.xml, NOT REQUIRED
#logging.config={path to logback config file}
## overwrite default levels file, e.g., /etc/crczp/default-levels.json, NOT REQUIRED
#path.to.default.levels={path to file with default levels}
## set logger levels using pattern logging.level.<logger-name>=<level>, NOT REQUIRED
logging.level.cz.cyberrange.platform=DEBUG
cors.allowed.origins=*
crczp.identity.providers[0].issuer=https://172.19.0.22/keycloak/realms/CRCZP
crczp.identity.providers[0].userInfoEndpoint=https://172.19.0.22/user-and-group/api/v1/users/info

